name: CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  finish_feature:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitFlow
      run: |
        sudo apt-get update
        sudo apt-get install -y git-flow

    - name: Initialize GitFlow
      run: |
        git flow init -d

    - name: Finish feature branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch origin develop
        git checkout develop
        git pull origin develop
        git flow feature finish ${{ github.event.pull_request.head.ref }}
        git push origin develop

