# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "develop" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  finish_feature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "benzakouryoussef66@gmail.com"
          git config --global user.name "BENZ199"

      - name: Install GitFlow
        run: |
          sudo apt-get update
          sudo apt-get install -y git-flow

      - name: Finish feature branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/BENZ199/gittestpipe.git
          git flow init
          git checkout feature/test
          git flow feature finish test
          git push origin develop
